import type { NextPage } from 'next';
import Box from '@mui/material/Box';
// import Scrollbars from 'react-custom-scrollbars-2';

import HomePage from 'containers/home_page';

const Home: NextPage = () => {
    return (
        <Box flex={1} overflow="auto">
            {/* <Head>
                <title>Image Tools</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head> */}
            {/* <Box flex={1} overflow="auto"> */}
            <HomePage />
            {/* </Box> */}
        </Box>
    );
};

export default Home;
