import type { NextPage } from 'next';
import Head from 'next/head';
import Box from '@mui/material/Box';

import UserLayout from 'containers/user_layout';

const Home: NextPage = () => {
    return (
        <Box flex={1} display="flex">
            <Head>
                <title>Image Tools</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <UserLayout>
                <Box></Box>
            </UserLayout>
        </Box>
    );
};

export default Home;
